import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface ReportConfig {
  projectName: string;
  engineerName: string;
  notes: string;
  calculatorTitle: string;
  inputs: { label: string; value: string; unit: string }[];
  results: { label: string; value: string; unit: string }[];
  chartElementId?: string;
  steps?: { label: string; latex: string }[];
}

export async function generateReport(config: ReportConfig): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const W = 210;
  const margin = 20;
  const contentW = W - 2 * margin;
  let curY = margin;

  // Cover page
  pdf.setFillColor(45, 106, 79);
  pdf.rect(0, 0, W, 60, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(28);
  pdf.text('HydroCalc Report', margin, 35);
  pdf.setFontSize(14);
  pdf.text(config.calculatorTitle, margin, 48);

  curY = 75;
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(11);

  const addField = (label: string, value: string) => {
    pdf.setFont('helvetica', 'bold');
    pdf.text(label + ':', margin, curY);
    pdf.setFont('helvetica', 'normal');
    pdf.text(value, margin + 45, curY);
    curY += 7;
  };

  addField('Project', config.projectName || 'Untitled');
  addField('Engineer', config.engineerName || '—');
  addField('Date', new Date().toLocaleDateString());
  if (config.notes) {
    curY += 3;
    addField('Notes', config.notes);
  }

  // Input parameters
  curY += 10;
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Input Parameters', margin, curY);
  curY += 8;

  pdf.setFontSize(10);
  pdf.setFillColor(240, 247, 244);
  pdf.rect(margin, curY - 4, contentW, 7, 'F');
  pdf.setFont('helvetica', 'bold');
  pdf.text('Parameter', margin + 2, curY);
  pdf.text('Value', margin + 80, curY);
  pdf.text('Unit', margin + 120, curY);
  curY += 7;

  pdf.setFont('helvetica', 'normal');
  for (const inp of config.inputs) {
    pdf.text(inp.label, margin + 2, curY);
    pdf.text(inp.value, margin + 80, curY);
    pdf.text(inp.unit, margin + 120, curY);
    curY += 6;
    if (curY > 270) { pdf.addPage(); curY = margin; }
  }

  // Results
  curY += 8;
  if (curY > 240) { pdf.addPage(); curY = margin; }
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Results', margin, curY);
  curY += 8;

  pdf.setFontSize(10);
  pdf.setFillColor(240, 247, 244);
  pdf.rect(margin, curY - 4, contentW, 7, 'F');
  pdf.setFont('helvetica', 'bold');
  pdf.text('Parameter', margin + 2, curY);
  pdf.text('Value', margin + 80, curY);
  pdf.text('Unit', margin + 120, curY);
  curY += 7;

  pdf.setFont('helvetica', 'normal');
  for (const res of config.results) {
    pdf.text(res.label, margin + 2, curY);
    pdf.text(res.value, margin + 80, curY);
    pdf.text(res.unit, margin + 120, curY);
    curY += 6;
    if (curY > 270) { pdf.addPage(); curY = margin; }
  }

  // Chart screenshot
  if (config.chartElementId) {
    const chartEl = document.getElementById(config.chartElementId);
    if (chartEl) {
      try {
        const canvas = await html2canvas(chartEl, { scale: 2, backgroundColor: '#ffffff' });
        const imgData = canvas.toDataURL('image/png');
        const imgW = contentW;
        const imgH = (canvas.height / canvas.width) * imgW;

        if (curY + imgH + 10 > 280) { pdf.addPage(); curY = margin; }
        curY += 8;
        pdf.addImage(imgData, 'PNG', margin, curY, imgW, imgH);
        curY += imgH + 5;
      } catch {
        // chart capture failed — skip
      }
    }
  }

  // Footer on each page
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(`Generated by HydroCalc — Page ${i} of ${pageCount}`, W / 2, 290, { align: 'center' });
  }

  pdf.save(`${config.projectName || 'HydroCalc'}-report.pdf`);
}
